export const LIMITS = {
  MIN_DEPOSIT_EUR:  5,
  MAX_DEPOSIT_EUR:  500,
  MIN_DEPOSIT_CENTS: 500,
  MAX_DEPOSIT_CENTS: 50000,
  USERNAME_MIN:     3,
  USERNAME_MAX:     20,
  PASSWORD_MIN:     8,
  DEFAULT_PAGE_SIZE: 24,
  ADMIN_PAGE_SIZE:   50,
} as const;
